### ISSUE TITLE
Theme preview svg endpoint

### ISSUE THREAD

**Issue by eamodio** [vscodethemes/web#119]
IMO it would be so cool to be able to include a link/embed/screenshot from here directly on the README/vscode marketplace theme page. Now there is a little bit of a chicken and egg problem at the start, but... 😄

**Comment by jschr** [comment]
Yes! This is something I've thought about already. 

The syntax in the previews are already rendered as SVG so wouldn't be that far off to generate the entire preview as svg. 

I could provide an endpoint (ie. `/e/zhuangtongfa.Material-theme.svg`) that would return just the preview as an svg.

Do you think that would solve your use case? 

I may also consider generating a png too for twitter previews.

**Comment by eamodio** [comment]
Yeah, I think that would be awesome!

**Comment by sheafitzek** [comment]
FYI per vscode docs, the first line under "Publishing extensions" reads:

> Due to security concerns, vsce will not publish extensions which contain user provided SVG images

[link](https://code.visualstudio.com/docs/extensions/publish-extension#_publishing-extensions)

**Comment by jschr** [comment]
Good to know, it'll probably need to be a png then.

**Comment by jschr** [comment]
Theme previews for svg and png are now automatically generated:

- https://vscodethemes.com/e/zhuangtongfa.material-theme/one-dark-pro.svg?language=javascript
- https://vscodethemes.com/e/zhuangtongfa.material-theme/one-dark-pro.jpg?language=javascript
