### ISSUE TITLE
Html preview is incorrect

### ISSUE THREAD

**Issue by sainnhe** [vscodethemes/web#156]
This is what html looks like in [vscodethemes.com](https://vscodethemes.com/e/sainnhe.gruvbox-material):

![vscodethemes](https://user-images.githubusercontent.com/37491630/63752661-393e6580-c8e4-11e9-9c65-4e309419ead9.png)

And this is what it looks like in my vscode:

![Screenshot from 2019-08-27 16-00-03](https://user-images.githubusercontent.com/37491630/63752665-3cd1ec80-c8e4-11e9-837c-cfe575df4f2f.png)

This is my color scheme: [gruvbox-material](https://marketplace.visualstudio.com/items?itemName=sainnhe.gruvbox-material)

**Comment by jschr** [comment]
Hey thanks for reporting, looks like it's using a fallback property.

**Comment by hiukky** [comment]
Same problem. [Flate](https://vscodethemes.com/search?q=flate)

**Comment by jschr** [comment]
I've updated the underlying grammars used in the new site so I believe these issues are now fixed. Let me know if you notice any differences still.
