### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by Arnau-Ninerola** [vscodethemes/web#160]
I think it would be really useful if there was an option to sort themes. For example sort light themes that have most downloads. Or something like that.

**Comment by jschr** [comment]
Generally, I want themes to promote themselves with nice previews rather than rely on metrics like downloads. 

That being said I do think more sorting and category options would be nice and plan to add them. 

Thanks for the feedback.

**Comment by VictorioBerra** [comment]
+1 for sorting by "github stars"

Example: https://github.com/search?o=desc&q=vscode+theme&s=stars&type=Repositories

**Comment by jschr** [comment]
You can now sort by installs, trending and recently updated themes on the new site!
