### ISSUE TITLE
search by RGB codes / find similar themes

### ISSUE THREAD

**Issue by jydiw** [vscodethemes/web#206]
Since there are so many themes, a nice feature would be to search for themes by color. Some possible implementations:

- return themes that feature colors in a user-supplied list (or even from a color picker)
- return themes that exclude certain colors
- upon viewing an extension, have a list of "similar themes" below the window that the user could then have the option to view the full results as another page

Similarity could be sorted by color distance (I'll use cosine similarity as an example but there are probably better algorithms out there). One could parse the json `colors` values into a vector and then compute cosine similarity with other themes. You'd only need to parse the json whenever the theme gets updated, and computing cosine similarity is not too computationally expensive with the right packages.

**Comment by jschr** [comment]
Hey, thanks for the feedback. I've actually started a rewrite of this project focusing on being able to search by providing a color palette. Unfortunately life has gotten in the way and I haven't been able to work on it much lately. I hope to have time to work on it this fall/winter, with a release date aiming for early next year.

**Comment by jschr** [comment]
You can now search by similar colors with the query string: [vscodethemes.com?editorBackground=hex|142A44](https://vscodethemes.com/?editorBackground=hex%7C142A44)

Check out the README for more info!
