### ISSUE TITLE
Theme not matching preview on site

### ISSUE THREAD

**Issue by Sawtaytoes** [vscodethemes/web#210]
Is the site altering themes to make them look better? For instance, this Gruvbox Material Soft looks really slick on the site, but when I loaded it in VSCode, it doesn't look the same.

Why's that the case?

## Site
![image](https://user-images.githubusercontent.com/3948069/130202974-d7d879aa-aff2-463b-9986-5b96b078672f.png)

## VS Code
![image](https://user-images.githubusercontent.com/3948069/130203157-d60ea51d-6a82-4e92-8a40-9fc7a40b51b9.png)

**Comment by jschr** [comment]
I believe the new site fixes the incorrect syntax colors after updating the javascript grammar I was using.

Let me know if you notice any any differences still and I will take a look.
