### ISSUE TITLE
Wrong preview on discord

### ISSUE THREAD

**Issue by ImOver00** [vscodethemes/web#217]
https://vscodethemes.com/light -> Try send sending this to a friend of yours in discord (or in any type of channel, DM, discord server etc..)
It would preview dark themes for you, like this:
![wrongpreview](https://user-images.githubusercontent.com/74414474/147418924-8fcd0853-994b-4cab-bad2-60a793b91587.PNG)
Atleast change that image.

**Comment by jschr** [comment]
Thanks for the suggestion. I agree, ideally the preview image would better match the results but I might just use a more generic image that includes both light and dark images.

**Comment by jschr** [comment]
I've updated the previews for the individual theme pages so they're dynamic but since there are a lot more searching options now I'm going to stick with a static thumbnail for the main search page.
