### ISSUE TITLE
XadillaX.mir2 didn't shown

### ISSUE THREAD

**Issue by XadillaX** [vscodethemes/web#225]
Here's the marketplace URL: https://marketplace.visualstudio.com/items?itemName=XadillaX.mir2

And here's 404: https://vscodethemes.com/e/XadillaX.mir2

**Comment by jschr** [comment]
Due to hitting Algolia limits I've had to reduce the marketplace sync to happen only once a month. I will re-enable it at the beginning of April and your theme should show up then. 

Sorry for the delay, I hope to have a new version of the site up soon to address this.

**Comment by jschr** [comment]
Your theme is up on the new site: https://vscodethemes.com/e/xadillax.mir2
