### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by jschr** [vscodethemes/web#230]
Thumbs up if you'd like to see Rust added to the site.

**Comment by bitfl0wer** [comment]
:3 yes

**Comment by jschr** [comment]
I would like to add support for Rust soon. I don't have any experience with Rust so if anybody would like to provide some suggestions for the Rust code we show in the previews that would be helpful.

The code should:
- Be exactly 14 lines including empty lines (so that the font sizes remain the same across different languages)
- Be valid syntax and ideally a working program
- Include a comment

**Comment by jschr** [comment]
Rust has been added to the site. Thanks for the code snippet @leonovk
