### ISSUE TITLE
New theme add

### ISSUE THREAD

**Issue by mch-sg** [vscodethemes/web#238]
Hello,

I recently developed my own VSCode theme. Can I put it on your website?

GitHub https://github.com/mch-sg/afternoon-delight
Marketplace: https://marketplace.visualstudio.com/items?itemName=magnush.afternoon-delight

Looking forward to hearing from you,
Magnus

**Comment by jschr** [comment]
Themes are automatically pulled from the marketplace: [https://vscodethemes.com/e/magnush.afternoon-delight/afternoon-delight](https://vscodethemes.com/e/magnush.afternoon-delight/afternoon-delight).

Any updates you publish to the marketplace should show up on the site after a few minutes.
