### ISSUE TITLE
Publish @vscodethemes/utilities package

### ISSUE THREAD

**Issue by jonaskohl** [vscodethemes/web#240]
Are there any plans on making the `@vscodethemes/utilities` package used by this application public?

**Comment by jschr** [comment]
hey @jonaskohl, is there something specifically you're looking for from that package or are you trying to get this repo running locally?

I could make it public if there's interest, the only reason I haven't is that I just need to clean it up a bit first.

**Comment by jonaskohl** [comment]
Just for completenes sake, so vscodethemes could be set up locally in theory. Also, I'd be interested in the rendering of the preview images

**Comment by jschr** [comment]
I'll open source it later today or this week. It will be lacking in some documentation but I'd be happy to help guide you through local development if you go down that route.

**Comment by jschr** [comment]
Published: https://github.com/vscodethemes/utilities
