### ISSUE TITLE
Server error after turning on a filter

### ISSUE THREAD

**Issue by AlexBelz123** [vscodethemes/web#241]
![image](https://user-images.githubusercontent.com/60185570/191317331-ddc86790-571a-4102-b33e-f293205846db.png)
Choose light or dark theme and go to pagination. Click on the next page - see the error

**Comment by pb2002** [comment]
The same happens for me when i change sorting mode or when i search for a theme

**Comment by jschr** [comment]
Thanks, this should be fixed now.
