### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by weidmaster** [vscodethemes/web#244]
Thumbs up if you want PHP support. It gets different syntax then HTML/CSS and sometimes some themes are difficult to read for this language.

**Comment by jschr** [comment]
I would like to add support for PHP soon. It's been a long time since I've used PHP so if anybody would like to provide some suggestions for the PHP code we show in the previews that would be helpful. 

The code should:
- Be exactly 14 lines including empty lines (so that the font sizes remain the same across different languages)
- Be valid syntax and ideally a working program
- Include a comment

**Comment by davisenra** [comment]
I would like to suggest the following code:

```php
<?php

class Main
{
    // This is a comment
    private string $message = 'Hello World!';

    public function printMessage(): void
    {
        echo "{$this->message}\n";
    }
}

(new Main())->printMessage();
```

14 lines, has empty lines, valid syntax, working program and includes a comment, plus it follows the code styling defined by the community.

**Comment by brudermusscode** [comment]
I would like to upvote this. I like to change my themes regularly but there is no way to preview the PHP syntax, which is exhausting.

I suggest the following code:
```PHP
<?php

class Artist extends Model {
  /**
   * @var string
   */
  protected $table = "artists";

  public function new(string $name): self {
    return self::create([
      "name" => $name,
    ]);
  }
}
```

It features the extension of a class, a comment including an @-parameter, a protected class variable, a public function with a typed parameter and a set return type. It creates a new entry in the database using the create() function, which accepts an array as their parameter. This is usually used to create a new model object in Laravel's Eloquent ORM, which is a highly used framework nowadays.

**Comment by jschr** [comment]
PHP has been recently added to the site. Thanks for the suggestion.

**Comment by weidmaster** [comment]
Thank you very much @jschr ! I for sure will browse for more themes now.
