### ISSUE TITLE
Search doesn't pass titleBarActiveBackground to private API

### ISSUE THREAD

**Issue by AndrewIngram** [vscodethemes/web#249]
Search accepts a `titleBarActiveBackground` param, but the code that hits the undocumented private API doesn't pass this value through. Assuming this is a one line fix, but since I don't have access to the API, I can't verify it myself to make the PR.

https://github.com/vscodethemes/web/blob/main/app/clients/api.ts#L33-L42

**Comment by jschr** [comment]
Thanks for the report! I just pushed a fix. 

Are you building something on top of this project or do you have very specific taste in themes? I'm surprised you noticed!

**Comment by AndrewIngram** [comment]
I stumbled upon it when trying to identify a theme from a screenshot, saw that it supported searching based on color.

Though it did make me think about something that can take a screenshot as an input and magically identify the theme.

**Comment by jschr** [comment]
> take a screenshot as an input and magically identify the theme

That's the ultimate goal for this project (if I had the time). 

Some ideas of varying complexity I had on how to do this:
1. Select colors from a screenshot manually (might need to be a browser extension)
2. Upload a picture, extract the most dominant colors and search for themes with matching colors
3. Train an ML model to identify themes from VS Code screenshots

What do you think? Any other ways we could identify themes from a screenshot?
