### ISSUE TITLE
What font is used in the renders on the website?

### ISSUE THREAD

**Issue by notAkki** [vscodethemes/web#253]
The font here for example:
<img width="299" alt="text" src="https://user-images.githubusercontent.com/79669032/224456543-0758de98-a2ea-4f1c-844a-db903b8adde9.png">

This was answered previously but the solution provided directed to a github page but that page can no longer be found.

**Comment by jschr** [comment]
Hey, the font-family used is `'SFMono-Regular',Consolas,'Liberation Mono',Menlo,Courier,monospace'`

Here's where it's set in the code:
https://github.com/vscodethemes/utilities/blob/main/src/renderers.ts#L56

It's the same font-family Github uses as well.
