### ISSUE TITLE
Dark mode scrollbars 

### ISSUE THREAD

**Issue by Chetan-KK** [vscodethemes/web#254]
I think this website needs a good looking scrollbar cause everything is dark and only scrollbar is white it feels off at night.

**Comment by jschr** [comment]
Sounds like we just need to set [`color-scheme: dark` on `:root`](https://stackoverflow.com/questions/65940522/how-do-i-switch-to-chromes-dark-scrollbar-like-github-does) in [dark.css](https://github.com/vscodethemes/web/blob/main/app/styles/dark.css#L18). 

Thanks, will do. You're welcome to make a PR as well.

**Comment by jschr** [comment]
Your fix is live, thanks! Would be helpful if you could confirm if it looks better now.
