### ISSUE TITLE
How to generate images preview theme

### ISSUE THREAD

**Issue by lamhoang1256** [vscodethemes/web#260]
I am developing a vscodetheme and I find your vscode theme previews very nice and convenient. I want to ask is there any way to create such image. Thank you very much 😍

![image-vscode-theme](https://user-images.githubusercontent.com/61537853/234320624-3568b609-b016-45cf-a6cf-862d363ccab7.svg)

**Comment by jschr** [comment]
Thanks for the feedback! Unfortunately there isn't a way to generate the previews before publishing your theme. There's some discussion in https://github.com/vscodethemes/web/issues/224 about the possibility of adding a CLI tool in the future. 

Closing this issue in favour of tracking in the other one.
