### ISSUE TITLE
Sample code is invalid

### ISSUE THREAD

**Issue by mholt** [vscodethemes/web#261]
The Go sample code doesn't compile:

```go
struct config {
    port int
}

func main() {
    var cfg config

    flag.IntVar(&cfg.port, "port", 4000)
    flag.Parse()

    // Start the web server.
    addr := fmt.Printf(":%d", cfg.port)
    log.Fatal(http.ListenAndServe(addr, nil))
}
```

The type definition (the first line) should be:

```go
type config struct {
```

Where is the sample code from? I tried to submit a patch but couldn't trace it down.

**Comment by jschr** [comment]
Thanks for pointing this out. 

The templates are in a different repo that I’ve been procrastinating on cleaning up, unfortunately. I hope to make it easier for others to contribute in the future. 

Changing the language template requires I re-sync all themes so it will be a little bit before I get this fixed but will try ASAP.

**Comment by mholt** [comment]
No worries, I just got lost trying to follow the text back to where it lives. Didn't realize it had to re-sync all themes. Not a top priority. Thanks! :)

**Comment by jschr** [comment]
This has finally been fixed! Sorry it took so long 😅
