### ISSUE TITLE
Some api seems to be down

### ISSUE THREAD

**Issue by MrYakobo** [vscodethemes/web#263]
Hey vscodethemes, this is just a heads up that right now, some api seems to malfunction:

<img width="670" alt="Screenshot 2023-07-14 at 07 30 54" src="https://github.com/vscodethemes/web/assets/11942597/b069f8a9-2d4c-404c-8651-48c87d755ade">

```js
Application Error
SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON
    at async Ms.searchExtensions (worker.js:7669:728)
    at async by (worker.js:7720:13)
    at async Hn (worker.js:749:11)
    at async Promise.allSettled (index 1)
    at async Wh (worker.js:1560:131)
    at async worker.js:1677:141
    at async a (worker.js:6073:24)
```

That is on https://vscodethemes.com/?type=dark. Any type of query gives me that error.
It seems like the backend api used to query themes returns HTML now instead of JSON.

Thank you for an awesome product! :+1:

**Comment by jschr** [comment]
thanks for the heads up, this is fixed now
