### ISSUE TITLE
Nightfall theme is actually Nightly Theme

### ISSUE THREAD

**Issue by Kochiyama** [vscodethemes/web#264]
The theme named Nightfall Theme, is actually the Nightly Theme by Ayush Lal

[vscodethemes Nightfalll](https://vscodethemes.com/e/ayushl.nightfall-theme/nightfall-theme?language=go)

[correct theme](https://marketplace.visualstudio.com/items?itemName=Ayush-Lal.nightly-theme)

**Comment by jschr** [comment]
Because the extension was renamed it create a new one on the site. Here is the correct link: https://vscodethemes.com/e/Ayush-Lal.nightly-theme/nightly-theme 

I'm not currently handling this well. I need to detect renames somehow and create redirects. Created a new issue for this in #268
