### ISSUE TITLE
Theme not showing preview and erroring out

### ISSUE THREAD

**Issue by tyanderson91** [vscodethemes/web#265]
I have a theme, Rusty Venture by tyanderson91, that I have published on the Vscode marketplace. I have downloaded and used it as have a few others, so I know it works. It has a description in the package.json and the theme is json, so it meets the requirements of vscodethemes. It also shows up in the vscodethemes search. However, there is no preview shown, and when I click on the theme I get an inscrutable error page. This does not happen with most themes, so I presume there is some unwritten rule that I am not following with my extension.

**Comment by jschr** [comment]
Hey, I forced it to re-sync and it is showing up now: https://vscodethemes.com/e/tyanderson91.rusty-venture/rusty

Going to chalk this up to a one-time thing for now but I will need to do some more investigating if this happens again.
