### ISSUE TITLE
Would it be possible to add the Summercamp theme to the list?

### ISSUE THREAD

**Issue by csalmeida** [vscodethemes/web#267]
Hi all 👋

I made a theme a while ago and wanted to know what I can do to have it listed on vscodethemes.
I understand it needs to follow these requirements:

> 1. A description must exist in the [extension's manifest](https://code.visualstudio.com/api/references/extension-manifest)
> 2. Themes must be .json (.tmTheme files are not supported)

I believe the theme follow's both requirements but perhaps I am missing something?
The theme is open source and available here: https://github.com/csalmeida/summercamp-vscode-theme

Would be grateful for any help getting it listed, thanks a lot!

**Comment by jschr** [comment]
Hey, sorry for the delay but your theme is now on the site: https://vscodethemes.com/e/csalmeida.summercamp/summercamp

**Comment by csalmeida** [comment]
Hey @jschr, happy new year! 🎉
No worries, thank you for taking the time to add it to the list.
