### ISSUE TITLE
MacOS Classic is broken

### ISSUE THREAD

**Issue by corysimmons** [vscodethemes/web#271]
Just stumbled upon this bugged one.

https://vscodethemes.com/e/huacnlee.theme-macos-classic/macos-classic?language=javascript

![image](https://github.com/vscodethemes/web/assets/224636/48dc5154-770f-499f-ac0c-1ec5d10ede31)

**Comment by jschr** [comment]
This should be fixed in the latest release. Thanks for reporting and sorry for the late response.
