### ISSUE TITLE
Site theme search appears to be broken

### ISSUE THREAD

**Issue by arthvadrr** [vscodethemes/web#272]
Checked this on multiple devices and separate ISPs just to be sure, looks like an invalid token may have found its way into a request. 

![vscodethemes-search](https://github.com/vscodethemes/web/assets/54081465/7fe06bd8-5735-4069-9ffb-af1c3b69c80a)

The response is a `500 Internal Server Error`

Error occurs when searching from the homepage:
e.g. `https://vscodethemes.com/?text=some+search`

The error:

```SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON
    at async Fs.searchExtensions (worker.js:7706:728)
    at async Ay (worker.js:7757:13)
    at async Vn (worker.js:749:11)
    at async Promise.allSettled (index 1)
    at async Zh (worker.js:1560:131)
    at async worker.js:1677:141
    at async a (worker.js:6073:24)```

**Comment by jschr** [comment]
Thanks for reporting. This should be fixed now.

**Comment by arthvadrr** [comment]
Looks good, love the site thanks for keeping it up!
