### ISSUE TITLE
Application Error when opening a theme

### ISSUE THREAD

**Issue by surfinzap** [vscodethemes/web#273]
At the end of January 2024, I deprecated the previous [Bikkuri theme](https://marketplace.visualstudio.com/items?itemName=brano.b-theme) in favor of [a new Bikkuri theme](https://marketplace.visualstudio.com/items?itemName=brano.bikkuri-theme) with the new handle.
When I [open the theme in vs code themes](https://vscodethemes.com/e/brano.bikkuri-theme/bikkuri-dark-coal-and-lively?language=javascript); I get the following error:
![image](https://github.com/vscodethemes/web/assets/1387798/668275ca-094a-4acc-90c8-0d2f4abbab97)

What might be the issue?

**Comment by jschr** [comment]
hey, thanks for reporting. I manually ran a sync and it looks like it's all fixed up now: https://vscodethemes.com/e/brano.bikkuri-theme/bikkuri-dark-coal-and-lively?language=javascript
