### ISSUE TITLE
Screenshots should show sidebar - major part of theme

### ISSUE THREAD

**Issue by mika76** [vscodethemes/web#276]
As stated in title, one of the major parts of the theme is how the sidebar and tabs look - but the screenshots do not show that

**Comment by jschr** [comment]
Hey, thanks for the feedback. I can only show so much in the previews and my intention is to give you just enough before previewing in VS Code or VS Code for Web. At this time I don't plan on adding the sidebar to the previews.

**Comment by mika76** [comment]
I get it - but you could add it to the github readme - people check here too...
