### ISSUE TITLE
Cannot find theme in vscode marketplace

### ISSUE THREAD

**Issue by Kros-ZERO** [vscodethemes/web#280]
i found a theme on this website: https://vscodethemes.com/e/meerankhurshid.palm-tree/palm-tree
but when i click 'open with vscode' button, it jumps to vscode but no theme was shown
and i cannot find this theme in marketplace

is there any way to install this theme?

**Comment by jschr** [comment]
Hey, looks like this theme was deleted. I currently don't have an easy way to automate deleting themes at the moment but this is something I hope to improve in the future.
