### ISSUE TITLE
activityBar.activeBorder and tab.activeBorderTop properties are not displayed

### ISSUE THREAD

**Issue by Aluisio** [vscodethemes/web#281]
Hello, analyzing the theme previews (and also looking at the preview of my own extension https://vscodethemes.com/e/aluisiodeavila.fuedskeps-theme/fuedskeps-blue?language=javascript ) I noticed that the `activityBar.activeBorder` and `tab.activeBorderTop` properties are not being displayed in the theme preview images.

It would be interesting if this adjustment were made so that it was displayed correctly, because from my analysis many other extensions use these two properties to differentiate the theme variants, and in this case by not showing the colors of these properties, the preview of each variant is the same.

In the case of the `activityBar.activeBorder` property, it is currently only showing the color if the theme uses the `activityBar.foreground` property, however many themes do not use this property so as not to change the color of the icon, and only change the color of the border.

In the case of the `tab.activeBorderTop` property, it is currently only showing the `tab.activeBorder` property.

### Theme preview inside VSCode
![Theme preview inside VSCode](https://github.com/user-attachments/assets/a1420091-058f-4fbe-a8d6-cf21670fe133)

### Theme preview inside vscodethemes
![Theme preview inside vscodethemes](https://github.com/user-attachments/assets/bb30a163-0b16-43e0-bef1-d9048816c4a0)

**Comment by jschr** [comment]
Thanks for the feedback. I just launched a new version of the site which has several improvements to theme previews including the active border.

**Comment by Aluisio** [comment]
Hello @jschr  
Congratulations on updating the site.
The bottom border of the tabs is now showing, but the activityBar.activeBorder property is still not showing.
I also noticed that the git tab badge is misaligned, as you can see in the photo below.
![Screenshot 2024-10-22 at 13 44 09](https://github.com/user-attachments/assets/d1ec3d17-1b16-4fb3-be76-7775cda60f44)

**Comment by jschr** [comment]
You're right I missed adding `activityBar.activeBorder`. I opened a new issue: https://github.com/vscodethemes/web/issues/285 

As for the alignment I did intentionally add the badge to to the Git icon since at least for me that's the one that usually has the badge.

**Comment by Aluisio** [comment]
Perfect @jschr. Now the color of the activity bar is showing. Regarding the alignment of the badge, what I wanted to show is that the text “3” is misaligned. In this screenshot taken with the smartphone, the misalignment is more visible.
![image](https://github.com/user-attachments/assets/7a6ffed3-6a93-4666-a304-b235d58f67e6)

**Comment by jschr** [comment]
Thanks, I see the issue is iOS safari. I've opened a new issue: https://github.com/vscodethemes/web/issues/286
