### ISSUE TITLE
Error when searching themes

### ISSUE THREAD

**Issue by murilonicemento** [vscodethemes/web#282]
The theme search feature appears to be broken. When I perform a theme search, I receive an application error instead of the expected results.

```js
SyntaxError: Unexpected token '<', "<html>"... is not valid JSON
```

**Steps to reproduce**:

1. Go to the [vscodethemes.com](https://vscodethemes.com/) website.
2. Search for a theme (e.g., northeirn).

**Error displayed in the console**:

```js
SyntaxError: Unexpected token '<', "<html>"... is not valid JSON
    at async Fs.searchExtensions (worker.js:7706:728)
    at async Ay (worker.js:7757:13)
    at async Vn (worker.js:749:11)
    at async Promise.allSettled (index 1)
    at async Zh (worker.js:1560:131)
    at async worker.js:1677:141)
    at async a (worker.js:6073:24)
```

![image](https://github.com/user-attachments/assets/9dea2a54-cbaf-4042-b8f1-022c443916ef)

**Comment by jschr** [comment]
Thanks for reporting, should be fixed now.
