### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by jschr** [vscodethemes/web#59]
**Update**: I want to support more languages but it's going to cost more $$ (#148). Please suggest languages you'd like to see as I'll still only be able to support the most popular.

**Comment by ICA3DaR5** [comment]
If there is a bounty for this, I would gladly translate to Greek. Check my GitHub profile for previous work done on the subject.

**Comment by HectorM14** [comment]
I'd like to see Python. Maybe create a drop-down list of languages at the top of the site, and remove the tabs of languages that are included in each demo (at least for the dashboard showing all the themes).

**Comment by jschr** [comment]
Python will definitely be one of the next languages. Do you have any suggestions for the snippet to display in the preview? It would ideally by the same number of lines as the current preview (14). 

I'm also thinking something similar for the drop-down. Maybe even a multi-select.

**Comment by HectorM14** [comment]
This is 14 lines and should demonstrate the color schemes. How would multi-select look?

```python
import os

"""A string"""

# A comment

class Foo(object):
    def __init__(self):
        bar = 42
        print(bar)
	
	@property
	def color(self):
		return 'Green'
```

**Comment by jschr** [comment]
This is great, thanks for doing that.

With a multi-select you could pick up to 3 languages to replace the current tabs. Still very much in the idea phase—open to suggestions!

**Comment by HectorM14** [comment]
That would be nice, the list wouldn't get too long because you're limiting the breadth of languages as you mention in the first comment?

**Comment by jschr** [comment]
Yeah, there is a finite number of languages I can support. The languages that are added will be based on demand and help from the community. After adding a few more I'll have a more defined process for adding one that should make it easier for others to contribute.

**Comment by mdsitton** [comment]
I would suggest C# as well 👍

**Comment by anshulxyz** [comment]
Languages I'd like to see this project support:
- Go
- Rust
- Swift

**Comment by kylepeeler** [comment]
Would love to see Javascript include JSX syntax within it, or a seperate JSX/React option.

**Comment by divinedragon** [comment]
Java and Kotlin as well, please. Below are example snippets for FizzBuzz.

```java
public class FizzBuzz {

  public static void main(String[] args) {
    int num = 100;
    for (int i = 1; i <= num; i++) {
      if (((i % 5) == 0) && ((i % 7) == 0))
        System.out.println("fizzbuzz");
      else if ((i % 5) == 0)
        System.out.println("fizz");
      else if ((i % 7) == 0)
        System.out.println("buzz");
      else
        System.out.println(i);
    }
  }
}
```

```kotlin
fun fizzBuzz(num: Int): String {
    return when {
        (num % 3 == 0) -> "Fizz"
        (num % 5 == 0) -> "Buzz"
        (num % 3 == 0 && num % 5 == 0) -> "FizzBuzz"
        else -> "$num"
    }
}
```

**Comment by jschr** [comment]
The new site now supports 4 more languages: Python, Go, Java and C++.

I've opened separate requests for [C#](https://github.com/vscodethemes/web/issues/229), [Rust](https://github.com/vscodethemes/web/issues/230), [Swift](https://github.com/vscodethemes/web/issues/231) and [Kotlin](https://github.com/vscodethemes/web/issues/232)
